### PR TITLE
Mp3 - Text to Speech (from IBM Cloud)

### PR DESCRIPTION
**Pull request by ThaiQ**
Read Our WIKI
https://github.com/ThaiQ/IBMScholars/wiki/Create-mp3-files-using-IBM-Cloud's-Watson-Text-To-Speech-service

image

### CODE REVIEW

**Review by seemavora — APPROVED** [review]
W O W. this looks amazing.

**Comment by surabhigupta2029** [comment]
Thanks so much Thai! The wiki page is super helpful too

**Review by surabhigupta2029 — APPROVED** [review]
Thanks so much Thai! The wiki page is super helpful too

**Review by Annabel1054 — APPROVED** [review]
Good job!

**Pull request merged**
